import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Foundations',
      items: [{type: 'autogenerated', dirName: '01-foundations'}],
    },
    {
      type: 'category',
      label: 'Module 1: The Nervous System',
      items: [{type: 'autogenerated', dirName: '02-module-1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [{type: 'autogenerated', dirName: '03-module-2-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: The Brain',
      items: [{type: 'autogenerated', dirName: '04-module-3-brain'}],
    },
    {
      type: 'category',
      label: 'Module 4: VLA',
      items: [{type: 'autogenerated', dirName: '05-module-4-vla'}],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{type: 'autogenerated', dirName: '06-capstone'}],
    },
  ],
};

export default sidebars;
